---
environment:
  matrix:
    - PYTHON: "C:\\Python35-x64"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python37-x64"

skip_commits:
  files:
    - "*.md"
    - "LICENSE"

install:
  - "%PYTHON%\\python.exe -m pip install -U .[dev]"

build: false

test_script:
  - "%PYTHON%\\python.exe -m pytest"
