---
environment:
  matrix:
    - PYTHON: "C:\\Python37-x64"
    - PYTHON: "C:\\Python38-x64"

skip_commits:
  files:
    - "*.md"
    - "LICENSE"

install:
  - "%PYTHON%\\python.exe -m pip install pipenv"
  - "%PYTHON%\\python.exe -m pipenv install --dev"

build: false

test_script:
  - "%PYTHON%\\python.exe pipenv run pytest"
